apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/part-of: kograph

resources:
  - config.yaml
  - service.yaml
  - deployment.yaml

images:
  - name: kograph-mcp
    newTag: dev
